# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Fabio Rosado
email: fabiorosado@outlook.com
description: > # this means to ignore newlines until "baseurl:"
 My time is divided between flying and coding
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
author: FabioRosado

# Analytics
google_analytics: UA-109089626-1

# Footer Contact Area
footer_text: Please feel free to contact me. <br> I'm always happy to chat!

# Social Media Usernames
github_username:  FabioRosado
twitter_username: FabioRosado_
instagram_username: FabioRosado
linkedin_username: fabiorosado
disqus_username: FabioRosado

# Blog Categories
default_icon: <i class="fa fa-asterisk" aria-hidden="true"></i>
category_one: code
category_one_icon: <i class="fa fa-code" aria-hidden="true"></i>
category_two: git
category_two_icon: <i class="fa fa-code-fork" aria-hidden="true"></i>
category_three: python
category_three_icon: 
category_four: random
category_four_icon: <i class="fa fa-random" aria-hidden="true"></i>


# Build settings
markdown: kramdown
remote_theme: niebieski 
highlighter: rouge
permalink: /:categories/:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag

include: ['_pages']

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
